In [1]:
%magic

In [2]:
a=[1,2,3]

In [3]:
b=a

In [6]:
a.append(4)

In [7]:
a

[1, 2, 3, 4]

In [8]:
b

[1, 2, 3, 4]

In [9]:
a=5

In [10]:
isinstance(5,int)

True

In [11]:
isinstance(5,str)

False

In [12]:
isinstance(5,(int,str))

True

In [13]:
a==b

False

In [14]:
a

5

In [15]:
b

[1, 2, 3, 4]

In [16]:
a=list(b)

In [17]:
a=b

In [18]:
a==b

True

In [19]:
n=None

In [20]:
n is None

True

In [21]:
s='python'

In [22]:
list(s)

['p', 'y', 't', 'h', 'o', 'n']

In [23]:
s[1]

'y'

In [24]:
s[:2]

'py'

In [25]:
datetime?

Object `datetime` not found.


In [26]:
import datetime

In [27]:
datetime?

In [30]:
from datetime import datetime

In [32]:
dt=datetime(2019,2,26,20,11,14)

In [33]:
dt.year

2019

In [34]:
dt.month

2

In [35]:
dt.day

26

In [36]:
dt.hour

20

In [37]:
dt.minute

11

In [38]:
dt.second

14

In [1]:
import numpy as np

In [2]:
data = {i:np.random.randn() for i in range(7)}

In [3]:
data

{0: 0.06588256749846379,
 1: -1.0331809437040882,
 2: 1.6061528641379357,
 3: -0.19394808845647837,
 4: 0.10986234347003886,
 5: 0.32768222938330016,
 6: -0.15031149602405425}

In [4]:
a_b=1

In [5]:
a_e=2

In [6]:
a_b

1

In [8]:
import datetime

In [9]:
datetime.MAXYEAR

9999

In [10]:
b=[1,2,3]

In [11]:
b?

In [12]:
print?

In [17]:
x = 5
y = 7
if x > 5:
    x += 1
    y = 8

In [19]:
np.random.randn?

In [20]:
np.random.randn(1)

array([1.80890225])

In [21]:
np.random.randn(1,2)

array([[0.9371262 , 0.03788982]])

In [22]:
np.random.randn(100,100)

array([[-1.63371337,  1.28696782,  0.69932125, ...,  0.5646815 ,
        -0.05584124, -0.98399394],
       [ 1.00756706,  0.39528211, -0.13216692, ..., -0.58311768,
         0.46247279,  0.62971189],
       [-0.53306144,  1.68736804,  1.52601832, ..., -0.29991446,
        -0.91332509, -1.9694851 ],
       ...,
       [ 0.91198798,  0.63623594,  0.1385659 , ..., -1.26429681,
         2.44538962, -1.432345  ],
       [ 0.38347058, -2.3121894 ,  1.40351963, ...,  0.39019477,
        -1.76973336,  0.48329073],
       [ 1.84913775, -1.49812168, -0.0036592 , ...,  0.11775296,
         0.2298756 ,  0.38181516]])

In [23]:
int(3.14)

3

In [24]:
x=5

In [25]:
'nonenegtative' if x>=0 else 'negative'

'nonenegtative'

In [26]:
#三元表达式