In [1]:
import pandas as pd

In [4]:
obj=pd.Series([4,7,-2,1])

In [5]:
obj

0    4
1    7
2   -2
3    1
dtype: int64

In [6]:
#Series的字符串表现形式为：索引在左，值在右。

In [10]:
obj.values #Series的值

array([ 4,  7, -2,  1], dtype=int64)

In [11]:
obj.index #like range(4)

RangeIndex(start=0, stop=4, step=1)

In [12]:
obj2=pd.Series([3,-4,1,7],index=['a','b','c','e'])

In [13]:
obj2

a    3
b   -4
c    1
e    7
dtype: int64

In [14]:
obj2.index

Index(['a', 'b', 'c', 'e'], dtype='object')

In [16]:
obj2['e']

7

In [20]:
obj2[['e','c','a']] #需要两个[[]]否则会报错，外圈[]是取位置，内圈[]是list，是索引列表

e    7
c    1
a    3
dtype: int64

In [21]:
obj2[obj2>1]

a    3
e    7
dtype: int64

In [22]:
obj2**2

a     9
b    16
c     1
e    49
dtype: int64

In [24]:
'2' in obj2

False

In [25]:
'e' in obj2

True

In [26]:
'3' in obj2

False

In [27]:
#显然，只能查找index，而不能查找值在不在Seires中

In [28]:
sdata={'a':100,'b':2,'c':-89}

In [29]:
pd.Series(sdata)

a    100
b      2
c    -89
dtype: int64

In [30]:
pd.Series([1,Null,-4,7,Null])

NameError: name 'Null' is not defined

In [31]:
pd.Series([1,,-4,7,])

SyntaxError: invalid syntax (<ipython-input-31-caf12805928c>, line 1)

In [32]:
pd.Series([1,NaN,-4,7,NaN])

NameError: name 'NaN' is not defined

In [33]:
pd.isnull(obj2)

a    False
b    False
c    False
e    False
dtype: bool

In [35]:
obj2.name='popular'

In [36]:
obj2

a    3
b   -4
c    1
e    7
Name: popular, dtype: int64

In [37]:
obj2.index.name='indexx'

In [38]:
obj2

indexx
a    3
b   -4
c    1
e    7
Name: popular, dtype: int64

In [39]:
obj.index=['aa','bb','cc','ee']

In [40]:
obj

aa    4
bb    7
cc   -2
ee    1
dtype: int64

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada',
'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [42]:
frame=pd.DataFrame(data)

In [43]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
frame.head

<bound method NDFrame.head of     state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2>

In [45]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [47]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=[1,2,3,4,5,6])

In [48]:
frame2

year   state  pop debt
1  2000    Ohio  1.5  NaN
2  2001    Ohio  1.7  NaN
3  2002    Ohio  3.6  NaN
4  2001  Nevada  2.4  NaN
5  2002  Nevada  2.9  NaN
6  2003  Nevada  3.2  NaN

In [49]:
pd.isnull(frame2)

year  state    pop  debt
1  False  False  False  True
2  False  False  False  True
3  False  False  False  True
4  False  False  False  True
5  False  False  False  True
6  False  False  False  True

In [50]:
frame2['NaN']=0

In [51]:
frame2

year   state  pop debt  NaN
1  2000    Ohio  1.5  NaN    0
2  2001    Ohio  1.7  NaN    0
3  2002    Ohio  3.6  NaN    0
4  2001  Nevada  2.4  NaN    0
5  2002  Nevada  2.9  NaN    0
6  2003  Nevada  3.2  NaN    0

In [52]:
frame2.T

1     2     3       4       5       6
year   2000  2001  2002    2001    2002    2003
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9     3.2
debt    NaN   NaN   NaN     NaN     NaN     NaN
NaN       0     0     0       0       0       0

In [53]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, 0],
       [2001, 'Ohio', 1.7, nan, 0],
       [2002, 'Ohio', 3.6, nan, 0],
       [2001, 'Nevada', 2.4, nan, 0],
       [2002, 'Nevada', 2.9, nan, 0],
       [2003, 'Nevada', 3.2, nan, 0]], dtype=object)

In [54]:
frame2.index

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [55]:
frame2.index.name='year'

In [56]:
frame2.columns.name='state'

In [57]:
frame2

state  year   state  pop debt  NaN
year                              
1      2000    Ohio  1.5  NaN    0
2      2001    Ohio  1.7  NaN    0
3      2002    Ohio  3.6  NaN    0
4      2001  Nevada  2.4  NaN    0
5      2002  Nevada  2.9  NaN    0
6      2003  Nevada  3.2  NaN    0

In [58]:
frame2.name='population'

In [59]:
frame2

state  year   state  pop debt  NaN
year                              
1      2000    Ohio  1.5  NaN    0
2      2001    Ohio  1.7  NaN    0
3      2002    Ohio  3.6  NaN    0
4      2001  Nevada  2.4  NaN    0
5      2002  Nevada  2.9  NaN    0
6      2003  Nevada  3.2  NaN    0

In [60]:
frame2['close']=0

In [61]:
frame2

state  year   state  pop debt  NaN  close
year                                     
1      2000    Ohio  1.5  NaN    0      0
2      2001    Ohio  1.7  NaN    0      0
3      2002    Ohio  3.6  NaN    0      0
4      2001  Nevada  2.4  NaN    0      0
5      2002  Nevada  2.9  NaN    0      0
6      2003  Nevada  3.2  NaN    0      0

In [64]:
frame2.reindex([6,5,4,3,2,1])

state  year   state  pop debt  NaN  close
year                                     
6      2003  Nevada  3.2  NaN    0      0
5      2002  Nevada  2.9  NaN    0      0
4      2001  Nevada  2.4  NaN    0      0
3      2002    Ohio  3.6  NaN    0      0
2      2001    Ohio  1.7  NaN    0      0
1      2000    Ohio  1.5  NaN    0      0

In [4]:
import pandas as pd
import numpy as np

In [6]:
obj=pd.Series(np.arange(4),index=['a','b','c','d'])

In [7]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [8]:
obj['b']

1

In [9]:
obj[1]

1

In [10]:
obj[2:4]

c    2
d    3
dtype: int32

In [11]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [12]:
#pd.Series在检索时可以用index，也可以用值检索

In [13]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [14]:
obj[obj<2]

a    0
b    1
dtype: int32

In [15]:
#利用标签的切片和普通的切片不同，是左右都包含的

In [16]:
obj['b':'c']=5

In [17]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [18]:
#用切片还可以对部分进行设置

In [19]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three','four'])

In [20]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [21]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [22]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [24]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [26]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [27]:
#选取行的语法data[:2]十分方便。向[ ]传递单一的元素或列表，就可选择列。

In [28]:
???

Object `` not found.


# 用loc和iloc进行选取

In [29]:
data.loc['Ohio',['one','two']]

one    0
two    1
Name: Ohio, dtype: int32

In [31]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [32]:
data.iloc[2] #第3行

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [34]:
data.iloc[:,:3]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

注意下面的用法

In [35]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [36]:
data.loc[:,:'one']

one
Ohio        0
Colorado    4
Utah        8
New York   12

## loc用来index检索，iloc用来位置检索！

如果DataFrame对象相加，没有共用的列或行标签，结果都会是空

In [38]:
df1=pd.DataFrame({'A':[1,2]})

In [39]:
df2 = pd.DataFrame({'B': [3, 4]})

In [40]:
df1

A
0  1
1  2

In [41]:
df2

B
0  3
1  4

In [42]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [43]:
df1.add(df2,fill_value=0)

A    B
0  1.0  3.0
1  2.0  4.0

In [44]:
1/df1

A
0  1.0
1  0.5

In [46]:
df1.rdiv(1)

A
0  1.0
1  0.5

In [47]:
#1/df1=df1.rdiv(1)

In [48]:
frame = pd.DataFrame(np.random.randn(4, 3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [49]:
frame.abs()

b         d         e
Utah    0.677751  0.240543  0.383191
Ohio    0.471768  0.420760  0.291449
Texas   0.609260  0.064630  0.414230
Oregon  0.632129  0.007892  0.849751

In [50]:
f=lambda x:x.max()-x.min()

In [51]:
frame.apply(f)

b    1.287010
d    0.661303
e    1.232942
dtype: float64

In [54]:
frame.apply(f,axis=1)  #1是行

Utah      0.437207
Ohio      0.763218
Texas     0.673890
Oregon    1.481881
dtype: float64

# 排序和排名

In [55]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [56]:
obj.sort_index

<bound method Series.sort_index of d    0
a    1
b    2
c    3
dtype: int64>

In [57]:
obj.sort_values

<bound method Series.sort_values of d    0
a    1
b    2
c    3
dtype: int64>

In [58]:
#缺失值会被放到末尾

In [59]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0,1]})

In [60]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [61]:
frame.sort_values(by='a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [62]:
frame=pd.DataFrame({'a':[1,2,3],'b':[7,1,4]})

In [63]:
frame

a  b
0  1  7
1  2  1
2  3  4

In [64]:
frame.values

array([[1, 7],
       [2, 1],
       [3, 4]], dtype=int64)

# 第六章 数据加载、存储与文件格式

skiprpws 需要忽略的行数，从0开始算起

na_values 替换na的值

nrows 读取文件的多少行数