In [1]:
#元组固定长度，不可改变，创建元组最简单的方式，是用逗号分隔一列值

In [2]:
a=1,2,3

In [3]:
a

(1, 2, 3)

In [4]:
b=(1,2),3,(4,5)

In [5]:
b

((1, 2), 3, (4, 5))

In [6]:
tuple([1,2,3])

(1, 2, 3)

In [7]:
tuple('string')

('s', 't', 'r', 'i', 'n', 'g')

In [8]:
t=_

In [9]:
t[0]

's'

In [10]:
t[0:3]

('s', 't', 'r')

In [11]:
tup=tuple(['foo',[1,2],True])

In [12]:
tup[1]

[1, 2]

In [13]:
tup[1]=2

TypeError: 'tuple' object does not support item assignment

In [14]:
tup[1]==2

False

In [15]:
tup[1].append=3

AttributeError: 'list' object attribute 'append' is read-only

In [16]:
tup[1].append(3)

In [17]:
tup

('foo', [1, 2, 3], True)

In [18]:
(4,None,'foo')+'bar'+(6,0)

TypeError: can only concatenate tuple (not "str") to tuple

In [19]:
(4,None,'foo')+('bar')+(6,0)

TypeError: can only concatenate tuple (not "str") to tuple

In [20]:
(4,None,'foo')+('bar',)+(6,0)

(4, None, 'foo', 'bar', 6, 0)

In [21]:
#元组用+时，如有‘string’，一定要加（‘string’，）逗号！

In [22]:
('foo','bar')*4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

In [23]:
tup=(1,4,5)

In [24]:
a,b,c=tup

In [25]:
a

1

In [26]:
#元组的拆分

In [27]:
tup=(4,5,(6,7))

In [28]:
a,b,(c,d)=tup

In [29]:
d

7

In [30]:
c

6

In [31]:
a,b=1,2

In [32]:
a

1

In [33]:
b

2

In [34]:
b,a=a,b

In [35]:
a

2

In [36]:
b

1

In [37]:
values=1,2,3,4,5

In [38]:
a,b,*rest=values

In [39]:
*rest

SyntaxError: can't use starred expression here (<ipython-input-39-5a76c08199ae>, line 1)

In [40]:
rest

[3, 4, 5]

In [41]:
a,b,*r=values

In [42]:
r

[3, 4, 5]

In [43]:
#count统计出现频率

In [44]:
a=(1,1,2,3,4,5)

In [45]:
a.count(1)

2

In [46]:
#列表：长度可变，内容可以被修改，可以用方括号[]定义，或者用list函数

In [47]:
list(12,3,4)

TypeError: list expected at most 1 arguments, got 3

In [48]:
a=[1,2,3]

In [49]:
a

[1, 2, 3]

In [50]:
tup=('a','b','c')

In [51]:
b_list=list(tup)

In [52]:
_

[1, 2, 3]

In [53]:
b_list[1]

'b'

In [54]:
b_list[1]='d'

In [55]:
b_list

['a', 'd', 'c']

In [56]:
r=range(10)

In [57]:
r

range(0, 10)

In [58]:
list(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
r.append(11)

AttributeError: 'range' object has no attribute 'append'

In [60]:
r=list(r)

In [61]:
r.append(11)

In [62]:
r

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]

In [63]:
r.drop(11)

AttributeError: 'list' object has no attribute 'drop'

In [64]:
r.insert(2,'red')

In [65]:
r

[0, 1, 'red', 2, 3, 4, 5, 6, 7, 8, 9, 11]

In [66]:
r.pop(2)

'red'

In [67]:
r

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]

In [68]:
#pop是insert的逆运算，移除并返回指定位置的元素

In [69]:
#remove可以去除某值，会先寻找第一个值然后去除

In [70]:
c_list=[1,2,3,1]

In [71]:
c_list.remove(1)

In [72]:
c_list

[2, 3, 1]

In [73]:
2 in c_list

True

In [74]:
'2' in c_list

False

In [75]:
'2' not in c_list

True

In [76]:
#串联和组合列表

In [77]:
[1,None,'foo']+[1,2,(3,4)]

[1, None, 'foo', 1, 2, (3, 4)]

In [78]:
#extend可以添加多个元素

In [79]:
x=_

In [80]:
x.attend(7,8,(1,2),'bar')

AttributeError: 'list' object has no attribute 'attend'

In [81]:
x.extend(7,8,(1,2),'bar')

TypeError: extend() takes exactly one argument (4 given)

In [82]:
x.extend[7,8,(1,2),'bar']

TypeError: 'builtin_function_or_method' object is not subscriptable

In [83]:
x.extend([7,8,(1,2),'bar'])

In [84]:
#extend（里面还是list，所以要用[list，list]）

In [85]:
a=[1,3,4,5,6,7]

In [86]:
a.sort()

In [87]:
a

[1, 3, 4, 5, 6, 7]

In [88]:
a=[6,4,1,2,4]

In [89]:
a.sort()

In [90]:
a

[1, 2, 4, 4, 6]

In [91]:
b=['apple','banana','orange','sky','o']

In [92]:
b.sort(key=len)

In [93]:
b

['o', 'sky', 'apple', 'banana', 'orange']

In [94]:
#二分查找

In [95]:
import bisect

In [96]:
c=[1,2,2,2,3,4,7]

In [97]:
bisect.bisect(c,0)

0

In [98]:
bisect.bisect(c,1)

1

In [99]:
bisect.bisect(c,2)

4

In [100]:
bisect.bisect(c,3)

5

In [101]:
bisect.bisect?

In [102]:
c=[1,3,3,3,5,9]

In [103]:
bisect.bisect(c,6)

5

In [104]:
bisect.insert(c,7)

AttributeError: module 'bisect' has no attribute 'insert'

In [105]:
bisect.insort(c,7)

In [106]:
c

[1, 3, 3, 3, 5, 7, 9]

In [107]:
#bisect不会检查是否已经排好序，所以使用bisect不会报错，但是结果不一定正确

In [108]:
seq=[1,2,3,4,5,6,7]

In [109]:
seq[1:5]

[2, 3, 4, 5]

In [110]:
seq[1:5]=[6,6,6,6]

In [111]:
seq

[1, 6, 6, 6, 6, 6, 7]

In [112]:
seq[1:5,:2]

TypeError: list indices must be integers or slices, not tuple

In [113]:
seq[::2]

[1, 6, 6, 7]

In [114]:
seq[1:5,2]

TypeError: list indices must be integers or slices, not tuple

In [115]:
seq[1:5:2]

[6, 6]

In [116]:
#seq[a:b:x]表示从[a,b)切片，并且步长为x

In [117]:
c=['bar','foo','baz']

In [118]:
mapping={}

In [119]:
for i,v in c:
    mapping[v]=i

ValueError: too many values to unpack (expected 2)

In [120]:
for i,v in enumerate(c):
    mapping[v]=i

In [121]:
mapping

{'bar': 0, 'foo': 1, 'baz': 2}

In [122]:
for v,i in enumerate(c):
    mapping[v]=i

In [123]:
mapping

{'bar': 0, 'foo': 1, 'baz': 2, 0: 'bar', 1: 'foo', 2: 'baz'}

In [124]:
sorted([7,1,2,6,5,0])

[0, 1, 2, 5, 6, 7]

In [125]:
sorted(['horserace'])

['horserace']

In [126]:
sorted('horserace')

['a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [127]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [128]:
b=_

In [129]:
a=[1,2,3]

In [130]:
zipped=zip(a,b)

In [131]:
zipped

In [132]:
list(zipped)

[(1, ' '), (2, 'a'), (3, 'c')]

In [133]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [134]:
dict={}

In [135]:
d1={'a':'something','b':[1,2,3]}

In [136]:
d1

{'a': 'something', 'b': [1, 2, 3]}

In [137]:
d1[7]='a'

In [138]:
d1

{'a': 'something', 'b': [1, 2, 3], 7: 'a'}

In [139]:
d1[6]='b'

In [140]:
d1

{'a': 'something', 'b': [1, 2, 3], 7: 'a', 6: 'b'}

In [141]:
del d1[7]

In [142]:
d1

{'a': 'something', 'b': [1, 2, 3], 6: 'b'}

In [143]:
#del是返回的同时删除

In [144]:
d1.pop('b')

[1, 2, 3]

In [145]:
d1.pop(b)

TypeError: unhashable type: 'list'

In [146]:
#del是关键字删除法，pop方法

In [147]:
d1.update('a':'yes')

SyntaxError: invalid syntax (<ipython-input-147-ff9a3f12818f>, line 1)

In [148]:
d1.update({'a':'yes'})

In [149]:
d1

{'a': 'yes', 6: 'b'}

In [150]:
words = ['apple', 'bat', 'bar', 'atom', 'book']

In [151]:
by_letter = {}

In [154]:
for word in words:
    letter=word[0]
    if letter not in by_letter:
        by_letter[letter]=[word]
    else:
        by_letter[letter].append(word)

In [155]:
by_letter

{'a': ['apple', 'apple', 'atom'], 'b': ['bat', 'bat', 'bar', 'book']}

In [156]:
d={}

In [157]:
d[tuple([1,2,3])]=5

In [158]:
d

{(1, 2, 3): 5}

In [159]:
d[2]=4

In [160]:
d

{(1, 2, 3): 5, 2: 4}

In [161]:
d[c]=5

TypeError: unhashable type: 'list'

In [162]:
d['c']=5

In [163]:
d

{(1, 2, 3): 5, 2: 4, 'c': 5}

In [164]:
#集合是无序的不可重复的元素的集合。可以当做字典，但是只有键没有值。可以用两种方式构建集合：set函数或者尖括号set语句

In [165]:
set([1,2,2,2,5,3,6])

{1, 2, 3, 5, 6}

In [166]:
{2,2,1,3,5,0}

{0, 1, 2, 3, 5}

In [167]:
a={0,1,2,3,5}

In [168]:
b={2,2,5,9}

In [169]:
a.union(b)

{0, 1, 2, 3, 5, 9}

In [170]:
a|b

{0, 1, 2, 3, 5, 9}

In [171]:
#合并：union 或 \

In [172]:
a.intersection(b)

{2, 5}

In [173]:
a & b

{2, 5}

In [174]:
#交集：intersection 或 &

In [175]:
{1,2,3}=={2,3,1}

True

In [176]:
string=['a','as','bar','baby']

In [177]:
[string.upper() for x in string if len(x)>2]

AttributeError: 'list' object has no attribute 'upper'

In [178]:
[x.upper() for x in string if len(x)>2]

['BAR', 'BABY']

In [179]:
states = [' Alabama ', 'Georgia!', 'Georgia', 'georgia',
'FlOrIda',
.....: 'south carolina##', 'West virginia?']

SyntaxError: invalid syntax (<ipython-input-179-6d4dd16a4257>, line 3)

In [180]:
states = [' Alabama ', 'Georgia!', 'Georgia', 'georgia',
'FlOrIda', 'south carolina##', 'West virginia?']

In [181]:
import re

In [183]:
def clean_strings(strings):
    result=[]
    value=value.strip()
    value=re.sub('[?#!]','',value)
    value=value.title()
    result.append(value)
return result

SyntaxError: 'return' outside function (<ipython-input-183-d0a5681c5eea>, line 7)

In [184]:
def clean_strings(strings):
    result=[]
    value=value.strip()
    value=re.sub('[?#!]','',value)
    value=value.title()
    result.append(value)
    return result

In [186]:
clean_strings(states)

UnboundLocalError: local variable 'value' referenced before assignment

In [188]:
def clean_strings(strings):
    result=[]
    for value in strings
    value=value.strip()
    value=re.sub('[?#!]','',value)
    value=value.title()
    result.append(value)
    return result

SyntaxError: invalid syntax (<ipython-input-188-9b25b35d3a97>, line 3)

In [189]:
def clean_strings(strings):
    result=[]
    for value in strings:
        value=value.strip()
        value=re.sub('[?#!]','',value)
        value=value.title()
        result.append(value)
    return result

In [190]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [193]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

In [194]:
attempt_float(3.14)

3.14

In [195]:
attempt_float('abc')

'abc'

#Chapter4 

In [196]:
#p113

In [1]:
data=[7,6,5,8,9,1]

In [2]:
np.array(data)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.array(data)

array([7, 6, 5, 8, 9, 1])

In [5]:
data2=[[1,2],[3,4]]

In [6]:
np.array(data2)

array([[1, 2],
       [3, 4]])

In [7]:
arr2=_

In [8]:
arr2.shape

(2, 2)

In [9]:
arr2.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [10]:
arr2.dtype

dtype('int32')

In [11]:
array(data).dtype

NameError: name 'array' is not defined

In [12]:
np.array(data).dtype

dtype('int32')

In [13]:
range(4)

range(0, 4)

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
for i in range(4):
    print(i)

0
1
2
3


In [16]:
for i in np.arange(4):
    print(i)

0
1
2
3


In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
arr2d[2]

array([7, 8, 9])

In [19]:
arr2d[0][2]

3

In [20]:
arr3d=np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])

In [21]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr3d[0]=66

In [24]:
arr3d

array([[[66, 66, 66],
        [66, 66, 66]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will',
'Joe', 'Joe'])

In [26]:
data=np.random.randn(7,4)

In [27]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [28]:
data

array([[ 0.50293013, -0.6438801 , -0.48705935,  1.6043945 ],
       [ 0.38973166,  1.10860844,  0.12408653, -1.05214631],
       [-0.97560685,  0.12441502, -0.32188427, -0.57761119],
       [ 1.39788645,  0.47173568,  1.332261  , -0.52899026],
       [-0.35802608, -0.27278631,  0.03306977, -1.35025904],
       [ 0.26729561,  1.20228142, -0.11353496, -0.94552579],
       [-1.2136326 ,  0.72378246, -1.38154026, -0.00256041]])

In [29]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [30]:
data[names='Bob']

SyntaxError: invalid syntax (<ipython-input-30-8f976ad11979>, line 1)

In [31]:
data[names=='Bob']

array([[ 0.50293013, -0.6438801 , -0.48705935,  1.6043945 ],
       [ 1.39788645,  0.47173568,  1.332261  , -0.52899026]])

In [33]:
data[names=='Bob',:2]

array([[ 0.50293013, -0.6438801 ],
       [ 1.39788645,  0.47173568]])

In [34]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [35]:
data[~(names='Bob')]

SyntaxError: invalid syntax (<ipython-input-35-971f7238e899>, line 1)

In [36]:
data[~(names=='Bob')]

array([[ 0.38973166,  1.10860844,  0.12408653, -1.05214631],
       [-0.97560685,  0.12441502, -0.32188427, -0.57761119],
       [-0.35802608, -0.27278631,  0.03306977, -1.35025904],
       [ 0.26729561,  1.20228142, -0.11353496, -0.94552579],
       [-1.2136326 ,  0.72378246, -1.38154026, -0.00256041]])

In [37]:
data[data<0]=0

In [38]:
data

array([[0.50293013, 0.        , 0.        , 1.6043945 ],
       [0.38973166, 1.10860844, 0.12408653, 0.        ],
       [0.        , 0.12441502, 0.        , 0.        ],
       [1.39788645, 0.47173568, 1.332261  , 0.        ],
       [0.        , 0.        , 0.03306977, 0.        ],
       [0.26729561, 1.20228142, 0.        , 0.        ],
       [0.        , 0.72378246, 0.        , 0.        ]])

In [39]:
data[names=='Joe']=7

In [40]:
data

array([[0.50293013, 0.        , 0.        , 1.6043945 ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.12441502, 0.        , 0.        ],
       [1.39788645, 0.47173568, 1.332261  , 0.        ],
       [0.        , 0.        , 0.03306977, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [41]:
arr=np.array((8,4))

In [42]:
arr

array([8, 4])

In [43]:
for i in range(8):
    arr[i]=i

IndexError: index 2 is out of bounds for axis 0 with size 2

In [44]:
arr=np.empty((8,4))

In [45]:
arr

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  4.94065646e-324,  7.41098469e-321,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         4.94065646e-324],
       [             nan,              nan,  2.12199579e-314,
         0.00000000e+000],
       [-2.86955702e-197,  1.88807585e+224,  9.74677727e+188,
         7.33975241e-308],
       [ 3.78277835e-307,  3.56022682e-307,  9.34603679e-307,
         8.45584427e-307]])

In [46]:
for i in range(8):
    arr[i]=i

In [47]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [48]:
arr[[2,6,7]]

array([[2., 2., 2., 2.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [49]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [50]:
#以特定顺序选取行子集，用[[x,y]]即可

In [51]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [52]:
#从右往左数，最后一个是-1

In [53]:
a=_

In [54]:
a.T

array([[5., 3., 1.],
       [5., 3., 1.],
       [5., 3., 1.],
       [5., 3., 1.]])

In [55]:
np.sqrt(a)

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [1.        , 1.        , 1.        , 1.        ]])

In [56]:
np.exp(a)

array([[148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ],
       [ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [  2.71828183,   2.71828183,   2.71828183,   2.71828183]])

In [57]:
np.mean(a)

3.0

In [58]:
np.max(a)

5.0

In [59]:
np.sum(a)

36.0

In [60]:
np.sum(a,axis=0)

array([9., 9., 9., 9.])

In [61]:
#1是行，0是列

In [62]:
np.cumsum(0)

array([0], dtype=int32)

In [63]:
np.array([0,1,2,4,5,6,7])

array([0, 1, 2, 4, 5, 6, 7])

In [64]:
a=_

In [65]:
np.cumsum(a)

array([ 0,  1,  3,  7, 12, 18, 25], dtype=int32)

In [66]:
arr=np.array([1,2,3],[4,5,6],[7,8,9])

ValueError: only 2 non-keyword arguments accepted

In [67]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [71]:
arr.cumsum

<function ndarray.cumsum>

In [72]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [74]:
arr=np.random.randn(100)

In [75]:
(arr>0).sum

<function ndarray.sum>

In [76]:
x=_

In [77]:
x

<function ndarray.sum>

In [78]:
#?为什么不是正值数的数目 P146

In [79]:
arr.sort

<function ndarray.sort>

In [81]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [82]:
#p159 完